version: '3'

services:
  postgres:
    image: 'postgres:13'
    container_name: 'airline'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: airline_db
    volumes:
      - postgres_data:/var/lib/postgresql/data



volumes:
  postgres_data: